### ISSUE TITLE
Add 1R1W "small fifo"

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#100]
Would use hardened 1R1W and a bsg_dff_en_bypass so that it can grab the read element out. Need to be careful about simultaneous read and write to same address of the 1R1W.

**Comment by taylor-bsg** [comment]
Also makes sense to add an equivalent version for bsg_async_fifo

**Comment by dpetrisko** [comment]
Does it make sense to have 'harden_p' as a parameter to the regular bsg_fifo_1r1w_small, since the changes should be fairly minimal?

**Comment by taylor-bsg** [comment]
I think it could make sense. Hardening will require a synchronous SRAM which make the changes less minimal then expected though.

**Comment by gaozihou** [comment]
Yeah I agree, we may want to slightly modify control logic to support bsg_mem_1r1w_sync.

One possible idea is that we add a port named **"rptr_n_o"** to **bsg_fifo_tracker** and **bsg_circular_ptr**. **"rptr_n_o"** is one cycle ahead of **"rptr_r_o"**, when attaching **"rptr_n_o"** to **bsg_mem_1r1w_sync**, the behavior will be same as before, latency of fifo will still be 1-cycle.

To deal with read-write-same-addr problem, as prof suggested, we may use a dff to hold the read data (just like what manycore regfile does).

**Comment by taylor-bsg** [comment]
To preserve single-cycle latency, we also need to bypass the write data
into the read data register, disabling the read enable on the ram.

I’m not sure if there is enough similarity in the logic to justify
extending the existing fifo tracker module; it may be easier to create a
new module.  I guess we will see...

M

**Comment by dpetrisko** [comment]
Close from #138?
