### ISSUE TITLE
[FIX LATER] bsg_cache does not support tag flush

### ISSUE THREAD

**Issue by gaozihou** [bespoke-silicon-group/basejump_stl#104]
https://github.com/bespoke-silicon-group/basejump_stl/blob/fa50804e78143c5b16c6d4010f9513083e8ef286/bsg_cache/bsg_cache.v#L125
Note that tagfl_op_tl_r is not used, tagfl_op_v_r is self assigned to 1'b0

**Comment by taylor-bsg** [comment]
Hi Tommy, if you close it, you should leave an indication of how it was resolved.

**Comment by tommydcjung** [comment]
https://github.com/bespoke-silicon-group/basejump_stl/pull/117

**Comment by taylor-bsg** [comment]
It still doesn’t support tagfl even with these changes — there is no logic to implement it?

**Comment by taylor-bsg** [comment]
Still does not support tagfl?

**Comment by tommydcjung** [comment]
it does, there is the logic in bsg_cache_miss.

**Comment by taylor-bsg** [comment]
ah okay!

Do you have some tests for this?

M

**Comment by tommydcjung** [comment]
https://github.com/bespoke-silicon-group/basejump_stl/pull/124
