### ISSUE TITLE
deprecate?

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#125]
https://github.com/bespoke-silicon-group/basejump_stl/blob/a1471e4cdf59fecaf08034eaf072f11a6609a25d/bsg_noc/bsg_wormhole_router.v#L16

Is this router in use anywhere? Are we ready to deprecate it?

**Comment by dpetrisko** [comment]
Not used in BP

**Comment by dpetrisko** [comment]
Doesn't appear to be in manycore, other than a testbench filelist

**Comment by dpetrisko** [comment]
When we deprecate this, we should probably rename bsg_wormhole_router_generalized -> bsg_wormhole_router

**Comment by dpetrisko** [comment]
#137
