### ISSUE TITLE
Assertion violates 'Be "pure" in your logical expressions.' from coding guidelines

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#144]
https://github.com/bespoke-silicon-group/basejump_stl/blob/89080b2a11a238df48ce4b55d6e55c6d223f66c2/hard/gf_14/bsg_mem/bsg_mem_2r1w_sync.v#L117

**Comment by dpetrisko** [comment]
Fixed in #147
