### ISSUE TITLE
bsg_mux_bitwise/bsg_mux_segmented parameter typo

### ISSUE THREAD

**Issue by tanglingshu** [bespoke-silicon-group/basejump_stl#154]
bsg_mux_bitwise calls on submodule bsg_mux_segmented. The parameter "segments_width_p" at line 16 differs from the bsg_mux_segmented parameter "segment_width_p".

**Comment by tanglingshu** [comment]
@tommydcjung

**Comment by stdavids** [comment]
Fixed in PR #155
