### ISSUE TITLE
[bsg_mem_1r1w] what is the use of r_v_i?

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/basejump_stl#165]
https://github.com/bespoke-silicon-group/basejump_stl/blob/ea91399294ae831e62527e00844bd7ec564ee809/bsg_mem/bsg_mem_1r1w.v#L22

What is the semantic of r_v_i? In the synth version, r_v_i is unused. Is the read supposed to be asynchronous?

Can this be just tied to zero?

**Comment by taylor-bsg** [comment]
r_v_i means you are reading the ram on that cycle. the read is
asynchronous. some implementations may have no use for the signal, but some
may.

M

**Comment by taylor-bsg** [comment]
It should not be tied to zero. =)
