### ISSUE TITLE
[bsg_sbox_ctrl] multiple issues

### ISSUE THREAD

**Issue by tanglingshu** [bespoke-silicon-group/basejump_stl#171]
Issue 1: Naming inconsistency (design name is bsg_sbox_ctrl.v but the module name is "bsg_sbox_ctrl_concentrate")

Issue 2: There is no "bsg_sort" submodule to be found

Issue 3: "bsg_stable_sort" is named "bsg_sort_4", which is an issue raised previously ( issue #170 )

**Comment by dpetrisko** [comment]
Fixed in #189
