### ISSUE TITLE
[bsg_cam_1r1w] "empty_v_o" assigned twice if "find_empty_entry_p=0"

### ISSUE THREAD

**Issue by tanglingshu** [bespoke-silicon-group/basejump_stl#184]
empty_v_o is assigned initially at line 51 and again at line 119 if "find_empty_entry_p=0". Suggested solution is to move the initial "empty_v_o" assignment from line 51 to inside of the if (find_empty_entry_p) loop, maybe at line 115. Special thanks to @dpetrisko for the help.

**Comment by dpetrisko** [comment]
Closing, no longer relevant after CAM refactor
