### ISSUE TITLE
bsg_dlatch should use always_latch

### ISSUE THREAD

**Issue by dpetrisko** [bespoke-silicon-group/basejump_stl#21]
...to match design intent

https://github.com/bespoke-silicon-group/basejump_stl/blob/3585a9e120a163986d21f2dc5a67a82e7ace253a/bsg_misc/bsg_dlatch.v#L7

**Comment by black-parrot** [comment]
And Scott promised to have this signal an error unless somebody uses the parameter i_know_this_is_usually_a_bad_idea_p.

M

**Comment by stdavids** [comment]
Attempted fix in PR #39

**Comment by stdavids** [comment]
PR #39 accepted and merged.
