### ISSUE TITLE
[CLARITY] for single bit wires; replace logic foo; assign foo = XX; with wire foo = XX; 

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#24]
https://github.com/bespoke-silicon-group/basejump_stl/blob/57a74de8023234987cc1e58311d10878ddc6f96d/bsg_cache/bsg_cache.v#L60

**Comment by dpetrisko** [comment]
Why stop at single bit wires? 

wire [1:0] bar = XX works as well

**Comment by taylor-bsg** [comment]
Agreed; I just wrote this because for the code I was pointing at it is
mostly single bit wires. The important thing is not do to this for
structures, or things that you declare as logic, i..e logic foo = XX is bad.

M

**Comment by dpetrisko** [comment]
Think that (wire =) should go in the style guideline?

**Comment by taylor-bsg** [comment]
The guide mentioned you could do this, but did not proactively suggest
doing it -- I added it! Thank you.

M

**Comment by tommydcjung** [comment]
might be a good idea to create a module bsg_cache_pkt_decode. and not rely on the actual bit values of enum.

**Comment by taylor-bsg** [comment]
Maybe post a separate issue for this ..
