### ISSUE TITLE
comments for pseudo lru tree encode

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#248]
https://github.com/bespoke-silicon-group/basejump_stl/blob/2085a8bc632973a4c4e1f066b945dd05dd84da3f/bsg_misc/bsg_lru_pseudo_tree_encode.v#L48

A comment would be good here since this is pretty crazy code. :-)

**Comment by tommydcjung** [comment]
It's not so crazy once you see it in picture.
![image](https://user-images.githubusercontent.com/46542701/76344449-db410080-62be-11ea-892c-fb20da747b22.png)

**Comment by taylor-bsg** [comment]
Adding comment that corresponds to picture:

https://github.com/bespoke-silicon-group/basejump_stl/commit/974af0e2f7f7a1abfab4591d4974e4faa50eced5
