### ISSUE TITLE
Additional modules for bsg_fpu

### ISSUE THREAD

**Issue by dpetrisko** [bespoke-silicon-group/basejump_stl#25]
In order to support RV64F

1) Floating point divide (most likely implemented as FP inversion and then multiplication)
2) Floating point square root
3) Floating point classify (decode types of NaNs and subnormal numbers)

**Comment by dpetrisko** [comment]
4. FMA operations. From my understanding, because the rounding happens at the end of an FMA instruction, we cannot simply attach the multiplier to the adder as is.

**Comment by taylor-bsg** [comment]
Yep.

**Comment by taylor-bsg** [comment]
bsg_fpu has been largely replaced with https://github.com/bsg-external/HardFloat/, particularly for the RV64F/RV32F case.
