### ISSUE TITLE
cam clarity

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#261]
https://github.com/bespoke-silicon-group/basejump_stl/blob/0055c82a8d95f31f724768caea943965364d1ae6/bsg_mem/bsg_cam_1r1w.v#L4

Some stylistic mismatches (no _r, no _lo suffixes.)

Comments should make it clear which of the port bundles are synchronous and which are asynchronous.

en_i signal should be explained. what does it practically do, and why is it necessary? Why not just have individual request signals for each of the parallel functions the cam can do?

some comments describing corner cases and how they are handled would be useful; i.e. multiple matches, what happens when deleting and searching for empty or accessing happens at the same time?

**Comment by dpetrisko** [comment]
Fixed with CAM refactor?

**Comment by taylor-bsg** [comment]
Thanks
