### ISSUE TITLE
1RW sync bitmask does not build in verilator

### ISSUE THREAD

**Issue by dpetrisko** [bespoke-silicon-group/basejump_stl#3]
When you try to compile bsg_mem/bsg_mem_1rw_sync_mask_write_bit_synth.v with Verilator, you get this error:

%Error-BLKLOOPINIT: /home/petrisko/bitbucket/test/pre-alpha-release/basejump_stl/bsg_mem/bsg_mem_1rw_sync_mask_write_bit_synth.v:42: Unsupported: Delayed assignment to array inside for loops (non-delayed is ok - see docs)

Verilator does not like this construct
```
 always_ff @(posedge clk_i)
   if (v_i & w_i)
       for (i = 0; i < width_p; i=i+1)
         if (w_mask_i[i])
           mem[addr_i][i] <= data_i[i];
```

This would work functionally, but may not synthesize to the same, depending on compiler quality.

```
 always_ff @(posedge clk_i)
   if (v_i & w_i)
     mem[addr_i] <= (~wmask_i & mem[addr_i]) | (w_mask_i & data_i); 
```

**Comment by dpetrisko** [comment]
This is a fairly high priority fix because it breaks BlackParrot's Verilator build
@proftaylor

**Comment by dpetrisko** [comment]
Oh, actually this could probably be fixed by changing to mem_n semantics.  I'll experiment

**Comment by black-parrot** [comment]
What was the resolution?

**Comment by dpetrisko** [comment]
Made a PR to fix

**Comment by stdavids** [comment]
PR#4
