### ISSUE TITLE
[bsg_idiv_iterative] might be unnecessary buffer.

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/basejump_stl#341]
https://github.com/bespoke-silicon-group/basejump_stl/blob/5ac2a5fd51b3369745f4aab5f7dc13cc3484495d/bsg_misc/bsg_idiv_iterative.v#L138

**Comment by taylor-bsg** [comment]
I agree -- the bsg_buf and bsg_buf_ctrl's can be removed from this module.
These are inherited from days when CAD tools didn't work that well. Perhaps
that will result in some area savings in BP and the manycore?

M

**Comment by taylor-bsg** [comment]
see also https://github.com/bespoke-silicon-group/basejump_stl/issues/193

**Comment by taylor-bsg** [comment]
https://github.com/bespoke-silicon-group/basejump_stl/pull/343
