### ISSUE TITLE
Dlatch fixes

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#38]
https://github.com/bespoke-silicon-group/basejump_stl/blob/0a9b3a9ee26c233e126da93d3235db7ce8d598c9/bsg_misc/bsg_dlatch.v#L2

- Have input be clk_i and not en_i; we want these used in very specific cases (usually a negative clock dlatch, will grab and pass through the new value at the second half of the cycle).
- Use always_latch and not always_ff
- Add %m warning if it is instantiated; and i_know_this_is_a_bad_idea_p which disables the warning.

**Comment by stdavids** [comment]
Attempted fix in PR #39

**Comment by stdavids** [comment]
PR #39 accepted and merged.
