### ISSUE TITLE
BSG_ABSTRACT does not work for verilator toplevel

### ISSUE THREAD

**Issue by dpetrisko** [bespoke-silicon-group/basejump_stl#446]
verilator --cc -pvalue+width_p=2 -pvalue+els_p=2 bsg_mux.v

```
%Warning-PINMISSING: bsg_mux.v:30: Cell has missing pin: data_i
%Warning-PINMISSING: Use "/* verilator lint_off PINMISSING */" and lint_on around source to disable this message.
%Warning-PINMISSING: bsg_mux.v:30: Cell has missing pin: sel_i
%Warning-PINMISSING: bsg_mux.v:30: Cell has missing pin: data_o
%Error: Specified --top-module 'bsg_mux' isn't at the top level, it's under another cell 'bsg_mux__abstract'
%Error: Exiting due to 1 error(s), 3 warning(s)
%Error: Command Failed /usr/bin/verilator_bin --cc -pvalue\+width_p\=2 -pvalue\+els_p\=2 --top-module bsg_mux bsg_mux.v
```

Haven't thought about this too hard. Seems like a Verilator issue, but could also be related to the spec. We could raise an issue there as well?

**Comment by dpetrisko** [comment]
NOTE: This arises when using the concrete module as a toplevel in a file which has an abstract wrapper. When using it as a submodule, this is not an issue

**Comment by taylor-bsg** [comment]
Yeah use a real top level module

**Comment by dpetrisko** [comment]
doesn't work for linting or testing with verilator

**Comment by dpetrisko** [comment]
I mean one approach is to say you can't directly instantiate basejump modules (since we want to do this abstract param thing for everything eventually), but that's not great.

My suggestion is to add an ifdef BSG_ENABLE_ABSTRACT which disables the abstract instantiation

**Comment by taylor-bsg** [comment]
Where is the mux getting its inputs from?

**Comment by dpetrisko** [comment]
The non-verilated testbench. One can verilate a testbench as a toplevel (this is what we do as BP), but for other testing methodologies (cocotb, systemC integration, mocking certain large modules as done in certain large chips) this is insufficient

**Comment by taylor-bsg** [comment]
Does seem like a bug in verilator to me.

M

**Comment by dpetrisko** [comment]
https://github.com/verilator/verilator/issues/3014

**Comment by dpetrisko** [comment]
Not sure if it's a bug or we're misinterpreting the spec and other simulators/synthesizers are more generous
