### ISSUE TITLE
just include verilator DPI clock gen, so testbenches don't have to double instantiate everything?

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#462]
https://github.com/bespoke-silicon-group/basejump_stl/blob/e814aa67d7be4086cbe7cd162359af6bc1c56904/bsg_test/bsg_nonsynth_clock_gen.v#L23

**Comment by dpetrisko** [comment]
@drichmond What do you think?

To avoid:
![image](https://user-images.githubusercontent.com/2322266/126050227-2d45775f-2f96-472c-b101-a82324a339ed.png)
everywhere , bring the ifdef inside this module?

**Comment by drichmond** [comment]
Sounds great to me, see PR is already submitted and merged
