### ISSUE TITLE
DT and RT getting stuck sometimes

### ISSUE THREAD

**Issue by yunusdawji** [bespoke-silicon-group/basejump_stl#573]
Hi,

We notice that the DoubleTrouble and RealTrouble gets stuck when we running long programs or running hello world multiple times. Are you aware of such problems? We are running bison project on DT. Also we added a ILA on ASIC FPGA and we see that the rocket gets stuck waiting for a D-Cache or I-Cache tilelink request. Any pointer or suggestion will help.

Our clock frequency is also very low, so I doubt its a timing issue.

Yunus

**Comment by taylor-bsg** [comment]
Hi,

Unfortunately, it does ring a bell.  Either a bug in that version of Rocket
or in our interface code… IIRC, the Rocket host interface does polling,
that is asynchronous to the Rocket execution so it is not deterministic.
Definitely not our preferred way to implement this, we ditch the polling in
BlackParrot…

M

**Comment by taylor-bsg** [comment]
This may be of interest:

https://github.com/black-parrot-hdk/zynq-parrot

It runs BP inside the Zynq PL.

**Comment by yunusdawji** [comment]
ok thanks!
