### ISSUE TITLE
bsg_comm_link_master_calib_skip_rom.v is broken

### ISSUE THREAD

**Issue by flaviens** [bespoke-silicon-group/basejump_stl#598]
Hi there!

It looks like `bsg_comm_link_master_calib_skip_rom.v` is broken (two closing parentheses on line 4) and was actually generated by an older version of `bsg_ascii_to_rom.py`.

**Comment by taylor-bsg** [comment]
Thanks -- I think this was corrupted as part of our bulk source code massaging.
